name: Build containers

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        container:
          - centos-stream9
          - fedora-latest
          - fedora-rawhide
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.container }}
          tags: latest
          dockerfiles: |
            containers/${{ matrix.container }}.dockerfile
          extra-args: |
            --squash

      - name: Copy the container to root's storage
        run: |
          podman save ${{ matrix.container }} | sudo podman load
          sudo podman image list

      - name: Test the container
        run: ./test-container.sh
        env:
          CONTAINER_TO_TEST: ${{ matrix.container }}

      - name: Tag container
        run: |
          podman tag ${{ matrix.container }}:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.container }}

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ matrix.container }}
          registry: ${{ env.REGISTRY }}
