name: Build containers

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container:
          - centos-stream8
          - fedora-34
          - fedora-rawhide
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ matrix.IMAGE_NAME }}
          tags: ${{ matrix.container }}
          dockerfiles: |
            containers/${{ matrix.container }}.dockerfile

      - name: Test the container
        run: ./test-container.sh
        env:
          CONTAINER_TO_TEST: "${{ env.REGISTRY }}/${{ matrix.IMAGE_NAME }}:${{ matrix.container }}"

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
